#lang racket
(list "red" "green" "blue")
(list 1 2 3 4 5)
(length (list "hop" "skip" "jump"))
(list-ref (list "hop" "skip" "jupm") 0)
(list-ref (list "hop" "skip" "jupm") 1)
(append (list "hop" "skip") (list "jump"))
(reverse (list "hop" "skip" "jump"))
(member "fall" (list "hop" "skip" "jump"))
(member "jump" (list "hop" "skip" "jump"))